### DISCUSSION TITLE
Remove numbering from headings

### DISCUSSION THREAD

**Discussion by DMcP89** [emad-elsaid/xlog#69] [General]
When the html is generated it seems like the headings are being converted into an ordered list. Is there a way to avoid this?

For example if I have this markdown:
```
# Hello World
## This is heading 2
```
It will be rendered like this:
# 1. Hello World
## 1.1 This is heading 2

**Comment by emad-elsaid** [comment]
The numbers comes from the following:

1. it's defined as SCSS [here](https://github.com/emad-elsaid/xlog/blob/master/cmd/assets/styles.scss#L75)
2. The generated to CSS with `yarn build` executed in `./cms/assets` directory 

You can add CSS to your generated pages using `--custom-css` argument when running xlog . [ref](https://xlog.emadelsaid.com/Usage/#:~:text=of%20the%20page%0A%20%20%2D-,custom_css,-string%0A%20%20%20%20%09Custom%20CSS)

The custom CSS should set content for `h1-6:before` to empty here is an example

```css
.view h1:before { content: unset; }
.view h2:before { content: unset; }
.view h3:before { content: unset; }
.view h4:before { content: unset; }
.view h5:before { content: unset; }
.view h6:before { content: unset; }
```
